env:
    global:
        - REPO_DIR=uwsgi
        # Commit from your-project that you want to build
        - BUILD_COMMIT=2.0.19.1
        # pip dependencies to _build_ your project
        - BUILD_DEPENDS=""
        # pip dependencies to _test_ your project.  Include any dependencies
        # that you need, that are also specified in BUILD_DEPENDS, this will be
        # a separate install.
        - TEST_DEPENDS="pytest"
        # Use this to add a pre-release version to the end of the uWSGI version
        # e.g., a4, b1
        - APPEND_VERSION="post0"
        - MB_ML_VER=2010
        # Exclude SSL from the wheel builds
        - UWSGI_PROFILE=pyuwsginossl
        - PLAT=x86_64
        - UNICODE_WIDTH=32
        - secure: "DN5Ki0K6QaoXYth9mnCSlzb2O8HrrBMsUSa06FUbmZ/44ViiJWsjRWKt9/aLDVLFB2Q3850e2ojDb75+Ad89x23Uyi2LtDWuiivojl+dvPwPt2x1BFbhN2DilfYxIwciBykb36PQcnXs1aJx96hOzyULLXaqEwvZVGj2MomotvGt56WqZP4317Gh9dnTsyogRpxg+X8hdXShrqTASLl1t/5vV0Yv8rgAA9wNFCZT/qCijOq5lSTpAqxJy/eLcULYiGJLiffkJ+k24RKYtLk8ZbG7N/LC9MS3FpWHxloSM1jUyA3e51jgNwHgJyH7dT3Zc5KnHd02RFFR93HFRTT0iFayeoESqholBfzjiKWdBz/Lq1K+E+rH9fuyWy5+rC7YUCRuAZSc2I5ETxfd0+sSHJ7OJm86btOAgpIjVL5NLVpiEBpjmAhK6xBVxvdaGg6llHu0dFGg/yJrCFKZ5ms03/CDMEUobVNNLhfMdutDzoLR5ZRjUc0SKzTpcNnqhGBpaCLeucnQH8f2nrGMLN4V80eTARIPwX40Nmcb5xaWVbMG7NbSSaGZFOCIVuY+G82K+OF3pN5sTpPKBSypiCVFZdwbExRObTEvw8F3o/TGEU0eJ5J+U5x7LQ+Dw4YocuXXBlv9csUrIV9ZJaXO3wZkzzVfZlTTRXII2MGAxPBECnA="
        - secure: "BaiF3jX2rCablLUjAY7dC4W0bJn7nfzAYjxBqP9pNkiso+GeT/wMOLZVYJW+aLx8BYOexYSLnNmMH8eX24lo2fu/WL3WKAGN6bRlOff2fzpBDTmLcXjQU3VutdKvjW47+GtEd+H4Xj8qDxOreFzzv1RiIR9ZocQqKo6qhNbmm7trw7yp9MiNudAlZO4Z3WFdI4dzgMl78MSOobkVlYPrjTGT2qPOTNvT4HSgKe9y0xmLJzmKGIMdFitoyeHMfFe3ADdQ9TCSUOkz3yqZlihYonFCpanCqLKIEzLQR/fDYQgbSiSukbbS3i1LwIp1qZLrRwT2+HuAL8ExrZITv95ZqDd31b0mDehuriNVQfnM1sF3TYcgnUL/Sixad5huWSaglpS8fZ2HnHz7dusPyqwyerbaD7HZOLoPBGZX4rb2n5TGz3ORK7qFUvEnaTg8jmKtdjgjGVxR0YFwKGY1+q21ZatKOs/4tNTp+X1GM8/+v7GfF0Wt9kYnMZlrf1kdmzy6gZe3t7TSgZHwrzoXkS+3h6U2YnGy8xsBAuvMIu4M0TBmpnNxjO/hl7aewsLGt7loH9+kyWGiH+wMFrIi2nvFLESKNg0gEv7Dh4JR0annfI3mL683j4meLT+OqdVus9ENKQH3olctfWHZdW39x2p1rCsVfrV8/m0OkhR3nRZgMQk="

language: generic
services: docker
dist: xenial

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.7
#        - PLAT=i686
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.7
#        - PLAT=i686
#        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.5
#        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.6
#        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.7
#        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
      - MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
      - MB_PYTHON_VERSION=3.8
      - MB_PYTHON_OSX_VER=10.9
before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - ./patch-uwsgi-packaging.sh $REPO_DIR
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    - pip install awscli
    - |
        aws s3 cp --acl=public-read \
          ${TRAVIS_BUILD_DIR}/wheelhouse/* \
          s3://ll-hotwheels/pyuwsgi/$(python $REPO_DIR/setup.py --version)/
